### PR TITLE
Fixed bugs and added new functionality

### PR DESCRIPTION
**Pull request by raj1034**
Prevents adding duplicate memberships, adding duplicate perks and adding a perk to a membership that does not exist.

### CODE REVIEW

**Review by areebhaq14 — COMMENTED** [review]
What is the hashCode() method for? I know its generating a hash code for each object but do we need this? Maybe in the future?

**Comment by raj1034** [comment]
> What is the hashCode() method for? I know its generating a hash code for each object but do we need this? Maybe in the future?

the hashCode() method is used in conjunction with the equals() method to ensure duplicate objects do not get added.

**Review by santhosh808 — APPROVED** [review]
Looks good

**Comment by areebhaq14** [comment]
> > What is the hashCode() method for? I know its generating a hash code for each object but do we need this? Maybe in the future?
> 
> the hashCode() method is used in conjunction with the equals() method to ensure duplicate objects do not get added.

Alright sounds good, thanks

**Review by areebhaq14 — APPROVED** [review]
LGTM

**Pull request merged**
