### PR TITLE
Hjallad/milestone2.0

### PR DESCRIPTION
**Pull request by H-Jallad**

### CODE REVIEW

**Comment by H-Jallad** [comment]
This is just for landing page, login portal, and viewing/adding memberships. Will enhance more in future PRs. Just don't want to do too much at once.

#28 
#29

**Review by santhosh808 — COMMENTED** [review]
Should the CAA.png image be in the img folder? Other than that, looks good! I'll approve after your response.

**Comment by H-Jallad** [comment]
> Should the CAA.png image be in the img folder? Other than that, looks good! I'll approve after your response.

For now, yes

**Review by raj1034 — APPROVED** [review]

**Review by santhosh808 — APPROVED** [review]
Looks good

**Pull request merged**
